mod 'puppet-nginx', '1.1.0'
mod 'puppetlabs-concat'
mod 'puppetlabs-translate'
mod 'samuelson-dockeragent'
mod 'puppetlabs-docker'
mod 'puppetlabs-apt'
mod 'puppetlabs-stdlib'
mod 'puppetlabs-powershell'
mod 'puppetlabs-reboot'
